name: first workflow
on: workflow_dispatch
jobs:
  first job:
      runs on: ubuntu-latest
      steps:
        - name: print greetings
          run: echo "good morning"
        - name: print bye
          run: echo "bye done!!"
        
